

package com.squareup.metro.extensions.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.squareup.metro.extensions.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler/src/test/resources/box")
@TestDataPath("$PROJECT_ROOT")
public class BoxTestGenerated extends AbstractBoxTest {
  @Test
  public void testAllFilesPresentInBox() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/src/test/resources/box"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Nested
  @TestMetadata("compiler/src/test/resources/box/contributesfeatureflag")
  @TestDataPath("$PROJECT_ROOT")
  public class Contributesfeatureflag {
    @Test
    public void testAllFilesPresentInContributesfeatureflag() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/src/test/resources/box/contributesfeatureflag"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("dynamicConfigurationFlag.kt")
    public void testDynamicConfigurationFlag() {
      runTest("compiler/src/test/resources/box/contributesfeatureflag/dynamicConfigurationFlag.kt");
    }

    @Test
    @TestMetadata("multiCompilation.kt")
    public void testMultiCompilation() {
      runTest("compiler/src/test/resources/box/contributesfeatureflag/multiCompilation.kt");
    }

    @Test
    @TestMetadata("multipleFlags.kt")
    public void testMultipleFlags() {
      runTest("compiler/src/test/resources/box/contributesfeatureflag/multipleFlags.kt");
    }

    @Test
    @TestMetadata("singleCompilation.kt")
    public void testSingleCompilation() {
      runTest("compiler/src/test/resources/box/contributesfeatureflag/singleCompilation.kt");
    }
  }

  @Nested
  @TestMetadata("compiler/src/test/resources/box/contributesmultibindingscoped")
  @TestDataPath("$PROJECT_ROOT")
  public class Contributesmultibindingscoped {
    @Test
    public void testAllFilesPresentInContributesmultibindingscoped() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/src/test/resources/box/contributesmultibindingscoped"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("excludedScopedBinding.kt")
    public void testExcludedScopedBinding() {
      runTest("compiler/src/test/resources/box/contributesmultibindingscoped/excludedScopedBinding.kt");
    }

    @Test
    @TestMetadata("hintGeneratedFir.kt")
    public void testHintGeneratedFir() {
      runTest("compiler/src/test/resources/box/contributesmultibindingscoped/hintGeneratedFir.kt");
    }

    @Test
    @TestMetadata("hintGeneratedIr.kt")
    public void testHintGeneratedIr() {
      runTest("compiler/src/test/resources/box/contributesmultibindingscoped/hintGeneratedIr.kt");
    }

    @Test
    @TestMetadata("multiCompilation.kt")
    public void testMultiCompilation() {
      runTest("compiler/src/test/resources/box/contributesmultibindingscoped/multiCompilation.kt");
    }

    @Test
    @TestMetadata("replacedScopedBinding.kt")
    public void testReplacedScopedBinding() {
      runTest("compiler/src/test/resources/box/contributesmultibindingscoped/replacedScopedBinding.kt");
    }

    @Test
    @TestMetadata("scopedInSuperTypes.kt")
    public void testScopedInSuperTypes() {
      runTest("compiler/src/test/resources/box/contributesmultibindingscoped/scopedInSuperTypes.kt");
    }

    @Test
    @TestMetadata("singleCompilation.kt")
    public void testSingleCompilation() {
      runTest("compiler/src/test/resources/box/contributesmultibindingscoped/singleCompilation.kt");
    }
  }

  @Nested
  @TestMetadata("compiler/src/test/resources/box/contributesrobot")
  @TestDataPath("$PROJECT_ROOT")
  public class Contributesrobot {
    @Test
    public void testAllFilesPresentInContributesrobot() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/src/test/resources/box/contributesrobot"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("componentAddedToGraph.kt")
    public void testComponentAddedToGraph() {
      runTest("compiler/src/test/resources/box/contributesrobot/componentAddedToGraph.kt");
    }

    @Test
    @TestMetadata("composeScreenRobot.kt")
    public void testComposeScreenRobot() {
      runTest("compiler/src/test/resources/box/contributesrobot/composeScreenRobot.kt");
    }

    @Test
    @TestMetadata("hintGeneratedFir.kt")
    public void testHintGeneratedFir() {
      runTest("compiler/src/test/resources/box/contributesrobot/hintGeneratedFir.kt");
    }

    @Test
    @TestMetadata("hintGeneratedIr.kt")
    public void testHintGeneratedIr() {
      runTest("compiler/src/test/resources/box/contributesrobot/hintGeneratedIr.kt");
    }

    @Test
    @TestMetadata("innerClassRobot.kt")
    public void testInnerClassRobot() {
      runTest("compiler/src/test/resources/box/contributesrobot/innerClassRobot.kt");
    }

    @Test
    @TestMetadata("multiCompilation.kt")
    public void testMultiCompilation() {
      runTest("compiler/src/test/resources/box/contributesrobot/multiCompilation.kt");
    }

    @Test
    @TestMetadata("screenRobot.kt")
    public void testScreenRobot() {
      runTest("compiler/src/test/resources/box/contributesrobot/screenRobot.kt");
    }
  }

  @Nested
  @TestMetadata("compiler/src/test/resources/box/contributesservice")
  @TestDataPath("$PROJECT_ROOT")
  public class Contributesservice {
    @Test
    public void testAllFilesPresentInContributesservice() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/src/test/resources/box/contributesservice"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("multiCompilation.kt")
    public void testMultiCompilation() {
      runTest("compiler/src/test/resources/box/contributesservice/multiCompilation.kt");
    }

    @Test
    @TestMetadata("replacedMultipleServices.kt")
    public void testReplacedMultipleServices() {
      runTest("compiler/src/test/resources/box/contributesservice/replacedMultipleServices.kt");
    }

    @Test
    @TestMetadata("replacedServiceOneCompilation.kt")
    public void testReplacedServiceOneCompilation() {
      runTest("compiler/src/test/resources/box/contributesservice/replacedServiceOneCompilation.kt");
    }

    @Test
    @TestMetadata("replacedServiceSameLibSeparateGraph.kt")
    public void testReplacedServiceSameLibSeparateGraph() {
      runTest("compiler/src/test/resources/box/contributesservice/replacedServiceSameLibSeparateGraph.kt");
    }

    @Test
    @TestMetadata("replacedServiceThreeCompilations.kt")
    public void testReplacedServiceThreeCompilations() {
      runTest("compiler/src/test/resources/box/contributesservice/replacedServiceThreeCompilations.kt");
    }

    @Test
    @TestMetadata("replacedServiceTwoCompilations.kt")
    public void testReplacedServiceTwoCompilations() {
      runTest("compiler/src/test/resources/box/contributesservice/replacedServiceTwoCompilations.kt");
    }

    @Test
    @TestMetadata("singleCompilation.kt")
    public void testSingleCompilation() {
      runTest("compiler/src/test/resources/box/contributesservice/singleCompilation.kt");
    }
  }

  @Nested
  @TestMetadata("compiler/src/test/resources/box/developmentappcomponent")
  @TestDataPath("$PROJECT_ROOT")
  public class Developmentappcomponent {
    @Test
    public void testAllFilesPresentInDevelopmentappcomponent() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/src/test/resources/box/developmentappcomponent"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("excludeLoggedInComponent.kt")
    public void testExcludeLoggedInComponent() {
      runTest("compiler/src/test/resources/box/developmentappcomponent/excludeLoggedInComponent.kt");
    }

    @Test
    @TestMetadata("multiCompilation.kt")
    public void testMultiCompilation() {
      runTest("compiler/src/test/resources/box/developmentappcomponent/multiCompilation.kt");
    }

    @Test
    @TestMetadata("singleCompilation.kt")
    public void testSingleCompilation() {
      runTest("compiler/src/test/resources/box/developmentappcomponent/singleCompilation.kt");
    }
  }
}
