

package com.squareup.metro.extensions.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.squareup.metro.extensions.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler/src/test/resources/diagnostics")
@TestDataPath("$PROJECT_ROOT")
public class FirDiagnosticTestGenerated extends AbstractFirDiagnosticTest {
  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/src/test/resources/diagnostics"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Nested
  @TestMetadata("compiler/src/test/resources/diagnostics/contributesmultibindingscoped")
  @TestDataPath("$PROJECT_ROOT")
  public class Contributesmultibindingscoped {
    @Test
    public void testAllFilesPresentInContributesmultibindingscoped() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/src/test/resources/diagnostics/contributesmultibindingscoped"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("classMustImplementScoped.kt")
    public void testClassMustImplementScoped() {
      runTest("compiler/src/test/resources/diagnostics/contributesmultibindingscoped/classMustImplementScoped.kt");
    }

    @Test
    @TestMetadata("replacedScopeMismatch.kt")
    public void testReplacedScopeMismatch() {
      runTest("compiler/src/test/resources/diagnostics/contributesmultibindingscoped/replacedScopeMismatch.kt");
    }
  }
}
