

package com.squareup.metro.extensions.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.squareup.metro.extensions.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler/src/test/resources/dump")
@TestDataPath("$PROJECT_ROOT")
public class FirDumpTestGenerated extends AbstractFirDumpTest {
  @Test
  public void testAllFilesPresentInDump() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/src/test/resources/dump"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Nested
  @TestMetadata("compiler/src/test/resources/dump/contributesfeatureflag")
  @TestDataPath("$PROJECT_ROOT")
  public class Contributesfeatureflag {
    @Test
    public void testAllFilesPresentInContributesfeatureflag() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/src/test/resources/dump/contributesfeatureflag"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("contributesFeatureFlag.kt")
    public void testContributesFeatureFlag() {
      runTest("compiler/src/test/resources/dump/contributesfeatureflag/contributesFeatureFlag.kt");
    }
  }

  @Nested
  @TestMetadata("compiler/src/test/resources/dump/contributesmultibindingscoped")
  @TestDataPath("$PROJECT_ROOT")
  public class Contributesmultibindingscoped {
    @Test
    public void testAllFilesPresentInContributesmultibindingscoped() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/src/test/resources/dump/contributesmultibindingscoped"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("contributesMultibindingScoped.kt")
    public void testContributesMultibindingScoped() {
      runTest("compiler/src/test/resources/dump/contributesmultibindingscoped/contributesMultibindingScoped.kt");
    }

    @Test
    @TestMetadata("scopedInSuperTypes.kt")
    public void testScopedInSuperTypes() {
      runTest("compiler/src/test/resources/dump/contributesmultibindingscoped/scopedInSuperTypes.kt");
    }
  }

  @Nested
  @TestMetadata("compiler/src/test/resources/dump/contributesrobot")
  @TestDataPath("$PROJECT_ROOT")
  public class Contributesrobot {
    @Test
    public void testAllFilesPresentInContributesrobot() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/src/test/resources/dump/contributesrobot"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("contributesRobot.kt")
    public void testContributesRobot() {
      runTest("compiler/src/test/resources/dump/contributesrobot/contributesRobot.kt");
    }
  }

  @Nested
  @TestMetadata("compiler/src/test/resources/dump/contributesservice")
  @TestDataPath("$PROJECT_ROOT")
  public class Contributesservice {
    @Test
    public void testAllFilesPresentInContributesservice() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/src/test/resources/dump/contributesservice"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("contributesService.kt")
    public void testContributesService() {
      runTest("compiler/src/test/resources/dump/contributesservice/contributesService.kt");
    }

    @Test
    @TestMetadata("replacedService.kt")
    public void testReplacedService() {
      runTest("compiler/src/test/resources/dump/contributesservice/replacedService.kt");
    }
  }

  @Nested
  @TestMetadata("compiler/src/test/resources/dump/developmentappcomponent")
  @TestDataPath("$PROJECT_ROOT")
  public class Developmentappcomponent {
    @Test
    public void testAllFilesPresentInDevelopmentappcomponent() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/src/test/resources/dump/developmentappcomponent"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("developmentAppComponent.kt")
    public void testDevelopmentAppComponent() {
      runTest("compiler/src/test/resources/dump/developmentappcomponent/developmentAppComponent.kt");
    }

    @Test
    @TestMetadata("excludeLoggedInComponent.kt")
    public void testExcludeLoggedInComponent() {
      runTest("compiler/src/test/resources/dump/developmentappcomponent/excludeLoggedInComponent.kt");
    }
  }
}
