

package com.squareup.metro.extensions.runners;

import com.intellij.testFramework.TestDataPath;
import org.jetbrains.kotlin.test.util.KtTestUtil;
import org.jetbrains.kotlin.test.TestMetadata;
import org.junit.jupiter.api.Nested;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.util.regex.Pattern;

/** This class is generated by {@link com.squareup.metro.extensions.GenerateTestsKt}. DO NOT MODIFY MANUALLY */
@SuppressWarnings("all")
@TestMetadata("compiler/src/test/resources/diagnostics")
@TestDataPath("$PROJECT_ROOT")
public class FirDiagnosticTestGenerated extends AbstractFirDiagnosticTest {
  @Test
  public void testAllFilesPresentInDiagnostics() {
    KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/src/test/resources/diagnostics"), Pattern.compile("^(.+)\\.kt$"), null, true);
  }

  @Nested
  @TestMetadata("compiler/src/test/resources/diagnostics/contributesfeatureflag")
  @TestDataPath("$PROJECT_ROOT")
  public class Contributesfeatureflag {
    @Test
    public void testAllFilesPresentInContributesfeatureflag() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/src/test/resources/diagnostics/contributesfeatureflag"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("dynamicConfigFlagMustBeObject.kt")
    public void testDynamicConfigFlagMustBeObject() {
      runTest("compiler/src/test/resources/diagnostics/contributesfeatureflag/dynamicConfigFlagMustBeObject.kt");
    }

    @Test
    @TestMetadata("mustBeObject.kt")
    public void testMustBeObject() {
      runTest("compiler/src/test/resources/diagnostics/contributesfeatureflag/mustBeObject.kt");
    }

    @Test
    @TestMetadata("mustBePublic.kt")
    public void testMustBePublic() {
      runTest("compiler/src/test/resources/diagnostics/contributesfeatureflag/mustBePublic.kt");
    }

    @Test
    @TestMetadata("mustImplementFeatureFlag.kt")
    public void testMustImplementFeatureFlag() {
      runTest("compiler/src/test/resources/diagnostics/contributesfeatureflag/mustImplementFeatureFlag.kt");
    }
  }

  @Nested
  @TestMetadata("compiler/src/test/resources/diagnostics/contributesmultibindingscoped")
  @TestDataPath("$PROJECT_ROOT")
  public class Contributesmultibindingscoped {
    @Test
    public void testAllFilesPresentInContributesmultibindingscoped() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/src/test/resources/diagnostics/contributesmultibindingscoped"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("classMustImplementScoped.kt")
    public void testClassMustImplementScoped() {
      runTest("compiler/src/test/resources/diagnostics/contributesmultibindingscoped/classMustImplementScoped.kt");
    }

    @Test
    @TestMetadata("replacedScopeMismatch.kt")
    public void testReplacedScopeMismatch() {
      runTest("compiler/src/test/resources/diagnostics/contributesmultibindingscoped/replacedScopeMismatch.kt");
    }
  }

  @Nested
  @TestMetadata("compiler/src/test/resources/diagnostics/contributesrobot")
  @TestDataPath("$PROJECT_ROOT")
  public class Contributesrobot {
    @Test
    public void testAllFilesPresentInContributesrobot() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/src/test/resources/diagnostics/contributesrobot"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("classMustExtendScreenRobot.kt")
    public void testClassMustExtendScreenRobot() {
      runTest("compiler/src/test/resources/diagnostics/contributesrobot/classMustExtendScreenRobot.kt");
    }
  }

  @Nested
  @TestMetadata("compiler/src/test/resources/diagnostics/contributesservice")
  @TestDataPath("$PROJECT_ROOT")
  public class Contributesservice {
    @Test
    public void testAllFilesPresentInContributesservice() {
      KtTestUtil.assertAllTestsPresentByMetadataWithExcluded(this.getClass(), new File("compiler/src/test/resources/diagnostics/contributesservice"), Pattern.compile("^(.+)\\.kt$"), null, true);
    }

    @Test
    @TestMetadata("classMustBeInterface.kt")
    public void testClassMustBeInterface() {
      runTest("compiler/src/test/resources/diagnostics/contributesservice/classMustBeInterface.kt");
    }

    @Test
    @TestMetadata("qualifierRequired.kt")
    public void testQualifierRequired() {
      runTest("compiler/src/test/resources/diagnostics/contributesservice/qualifierRequired.kt");
    }

    @Test
    @TestMetadata("tooManyQualifiers.kt")
    public void testTooManyQualifiers() {
      runTest("compiler/src/test/resources/diagnostics/contributesservice/tooManyQualifiers.kt");
    }
  }
}
