package com.squareup.metro.extensions.developmentapp

import com.squareup.metro.extensions.ClassIds
import com.squareup.metro.extensions.fir.findAnnotation
import dev.zacsweers.metro.compiler.MetroOptions
import dev.zacsweers.metro.compiler.api.fir.MetroContributionExtension
import dev.zacsweers.metro.compiler.compat.CompatContext
import dev.zacsweers.metro.compiler.fir.MetroFirTypeResolver
import org.jetbrains.kotlin.fir.FirSession
import org.jetbrains.kotlin.fir.expressions.FirAnnotationCall
import org.jetbrains.kotlin.fir.expressions.FirGetClassCall
import org.jetbrains.kotlin.fir.expressions.FirNamedArgumentExpression
import org.jetbrains.kotlin.fir.expressions.FirResolvedQualifier
import org.jetbrains.kotlin.fir.extensions.FirDeclarationPredicateRegistrar
import org.jetbrains.kotlin.fir.extensions.predicateBasedProvider
import org.jetbrains.kotlin.fir.resolve.defaultType
import org.jetbrains.kotlin.fir.resolve.providers.firProvider
import org.jetbrains.kotlin.fir.resolve.providers.symbolProvider
import org.jetbrains.kotlin.fir.symbols.impl.FirRegularClassSymbol
import org.jetbrains.kotlin.fir.types.ConeKotlinType
import org.jetbrains.kotlin.name.ClassId
import org.jetbrains.kotlin.name.Name

/**
 * Provides contribution metadata for the feature scope types generated by
 * [DevelopmentAppComponentFir] when `featureScope`/`featureComponent` are set.
 *
 * Generated types:
 * - `NoopLoginScreenComponent`: replaces `ContributedDevelopmentLoginScreenComponent` at
 *   ActivityScope
 * - `FeatureModule`: replaces `DefaultFeatureModule` at ActivityScope
 * - `FeatureLoginScreenComponent`: contributes to featureScope
 */
public class DevelopmentAppComponentMetroExtension(private val session: FirSession) :
  MetroContributionExtension {

  private val annotatedClasses by lazy {
    session.predicateBasedProvider
      .getSymbolsByPredicate(DevelopmentAppComponentIds.PREDICATE)
      .filterIsInstance<FirRegularClassSymbol>()
      .filter { readClassArgument(it, "featureScope") != null }
      .toList()
  }

  override fun FirDeclarationPredicateRegistrar.registerPredicates() {
    register(DevelopmentAppComponentIds.PREDICATE)
  }

  override fun getContributions(
    scopeClassId: ClassId,
    typeResolverFactory: MetroFirTypeResolver.Factory,
  ): List<MetroContributionExtension.Contribution> {
    return annotatedClasses.flatMap { classSymbol ->
      val featureScopeId =
        readClassArgument(classSymbol, "featureScope") ?: return@flatMap emptyList()
      buildList {
        if (scopeClassId == ClassIds.ACTIVITY_SCOPE) {
          // NoopLoginScreenComponent replaces ContributedDevelopmentLoginScreenComponent
          resolveContributionType(
              classSymbol.classId,
              DevelopmentAppComponentIds.NOOP_LOGIN_SCREEN_COMPONENT_NAME,
            )
            ?.let { type ->
              add(
                MetroContributionExtension.Contribution(
                  supertype = type,
                  replaces = listOf(ClassIds.CONTRIBUTED_DEVELOPMENT_LOGIN_SCREEN_COMPONENT),
                  originClassId = classSymbol.classId,
                )
              )
            }
        }

        if (scopeClassId == featureScopeId) {
          // FeatureLoginScreenComponent contributes to featureScope
          resolveContributionType(
              classSymbol.classId,
              DevelopmentAppComponentIds.FEATURE_LOGIN_SCREEN_COMPONENT_NAME,
            )
            ?.let { type ->
              add(
                MetroContributionExtension.Contribution(
                  supertype = type,
                  replaces = emptyList(),
                  originClassId = classSymbol.classId,
                )
              )
            }
        }
      }
    }
  }

  private fun resolveContributionType(parentClassId: ClassId, nestedName: Name): ConeKotlinType? {
    val nestedClassId = parentClassId.createNestedClassId(nestedName)
    val symbol =
      session.symbolProvider.getClassLikeSymbolByClassId(nestedClassId) as? FirRegularClassSymbol
        ?: return null
    return symbol.defaultType()
  }

  private fun readClassArgument(classSymbol: FirRegularClassSymbol, argName: String): ClassId? {
    val annotation =
      findAnnotation(classSymbol, ClassIds.DEVELOPMENT_APP_COMPONENT, session) ?: return null
    val annotationCall = annotation as? FirAnnotationCall ?: return null
    val name = Name.identifier(argName)
    val rawExpr =
      annotationCall.argumentMapping.mapping[name]
        ?: annotationCall.argumentList.arguments
          .filterIsInstance<FirNamedArgumentExpression>()
          .firstOrNull { it.name == name }
          ?.expression
    val getClassCall = rawExpr as? FirGetClassCall ?: return null
    val innerArg = getClassCall.argumentList.arguments.firstOrNull() ?: return null
    val classId =
      when (innerArg) {
        is FirResolvedQualifier -> innerArg.classId
        is org.jetbrains.kotlin.fir.expressions.FirPropertyAccessExpression -> {
          val ref = innerArg.calleeReference
          if (
            ref is org.jetbrains.kotlin.fir.references.FirResolvedNamedReference &&
              ref.resolvedSymbol is org.jetbrains.kotlin.fir.symbols.impl.FirClassLikeSymbol<*>
          ) {
            (ref.resolvedSymbol as org.jetbrains.kotlin.fir.symbols.impl.FirClassLikeSymbol<*>)
              .classId
          } else {
            val simpleName = ref.name
            val file = session.firProvider.getFirClassifierContainerFileIfAny(classSymbol)
            val fromImports =
              file?.imports?.firstNotNullOfOrNull { import ->
                if (import.isAllUnder) return@firstNotNullOfOrNull null
                val importedFqName = import.importedFqName ?: return@firstNotNullOfOrNull null
                if (importedFqName.shortName() == simpleName) {
                  val cid = ClassId.topLevel(importedFqName)
                  session.symbolProvider.getClassLikeSymbolByClassId(cid)?.classId
                } else null
              }
            fromImports
              ?: session.symbolProvider
                .getClassLikeSymbolByClassId(ClassId(classSymbol.classId.packageFqName, simpleName))
                ?.classId
          }
        }
        else -> null
      }
    if (classId?.asSingleFqName()?.asString() == "kotlin.Unit") return null
    return classId
  }

  public class Factory : MetroContributionExtension.Factory {
    override fun create(
      session: FirSession,
      options: MetroOptions,
      compatContext: CompatContext,
    ): MetroContributionExtension = DevelopmentAppComponentMetroExtension(session)
  }
}
