package com.squareup.test.demo

import android.app.Application
import com.squareup.development.shell.DevelopmentAppComponent
import dev.zacsweers.metro.createGraphFactory
import kotlin.test.Test
import kotlin.test.assertEquals
import kotlin.test.assertIs
import kotlin.test.assertNotNull

class DemoAppTest {
  @Test
  fun `generated MetroComponent can be created via factory`() {
    val factory = createGraphFactory<DemoApp.MetroComponent.Factory>()
    val component = factory.create(Application())
    assertIs<DemoApp.MetroComponent>(component)
  }

  @Test
  fun `factory implements DevelopmentAppComponent Factory`() {
    val factory = createGraphFactory<DemoApp.MetroComponent.Factory>()
    assertIs<DevelopmentAppComponent.Factory>(factory)
  }

  @Test
  fun `provideGraphFactory returns a working factory`() {
    val app = DemoApp()
    val factory = app.provideGraphFactory()
    assertIs<DevelopmentAppComponent.Factory>(factory)
    val component = factory.create(Application())
    assertNotNull(component)
  }

  @Test
  fun `same-module ContributesBinding is discovered for generated DependencyGraph`() {
    val factory = createGraphFactory<DemoApp.MetroComponent.Factory>()
    val component = factory.create(Application())
    // This verifies that DemoServiceImpl's @ContributesBinding(AppScope::class) is properly
    // merged into the MetroComponent generated by @DevelopmentAppComponent. Without the
    // name-based fallback in ContributedInterfaceSupertypeGenerator, the scope resolution
    // fails during the SUPERTYPES phase and DemoService cannot be provided.
    val service = (component as DemoServiceComponent).demoService
    assertEquals("contributed-binding", service.name)
  }
}
