package com.squareup.test.demo

import com.squareup.dagger.AppScope
import dev.zacsweers.metro.ContributesBinding
import dev.zacsweers.metro.ContributesTo
import dev.zacsweers.metro.Inject
import dev.zacsweers.metro.binding

/**
 * Reproduces a bug where @ContributesBinding contributions in the same module as a
 *
 * @DependencyGraph generated by an external FIR extension (@DevelopmentAppComponent) are not
 *   discovered during the SUPERTYPES phase.
 *
 * The @MetroContribution annotation's scope argument can't be resolved at the SUPERTYPES phase for
 * same-module classes in real Gradle compilations, causing the contribution to be silently dropped.
 */
interface DemoService {
  val name: String
}

@Inject
@ContributesBinding(AppScope::class, binding = binding<DemoService>())
class DemoServiceImpl : DemoService {
  override val name: String = "contributed-binding"
}

/** Exposes [DemoService] on the generated graph. */
@ContributesTo(AppScope::class)
interface DemoServiceComponent {
  val demoService: DemoService
}
