package com.squareup.metro.extensions.scoped

import com.fueledbycaffeine.autoservice.AutoService
import com.squareup.metro.extensions.fir.extractScopeClassId
import dev.zacsweers.metro.compiler.MetroOptions
import dev.zacsweers.metro.compiler.api.fir.MetroContributionExtension
import dev.zacsweers.metro.compiler.compat.CompatContext
import dev.zacsweers.metro.compiler.fir.MetroFirTypeResolver
import org.jetbrains.kotlin.fir.FirSession
import org.jetbrains.kotlin.fir.extensions.FirDeclarationPredicateRegistrar
import org.jetbrains.kotlin.fir.extensions.predicateBasedProvider
import org.jetbrains.kotlin.fir.resolve.defaultType
import org.jetbrains.kotlin.fir.resolve.providers.symbolProvider
import org.jetbrains.kotlin.fir.symbols.impl.FirRegularClassSymbol
import org.jetbrains.kotlin.name.ClassId

/**
 * Implements [MetroContributionExtension] to tell Metro's `ContributedInterfaceSupertypeGenerator`
 * about contributions from our generated `MultibindingScopedContribution` interfaces.
 *
 * This is necessary because Metro's predicate-based provider only sees source declarations and
 * declarations generated by generators that registered the predicate for `@ContributesTo`. Our
 * `MultibindingScopedContribution` is generated by [ContributesMultibindingScopedFir] (which
 * registered a predicate for `@ContributesMultibindingScoped`), so Metro's in-compilation discovery
 * doesn't see it.
 */
public class ContributesMultibindingScopedMetroExtension(private val session: FirSession) :
  MetroContributionExtension {

  private val predicate = ContributesMultibindingScopedIds.PREDICATE

  private val annotatedClasses by lazy {
    session.predicateBasedProvider
      .getSymbolsByPredicate(predicate)
      .filterIsInstance<FirRegularClassSymbol>()
      .toList()
  }

  override fun FirDeclarationPredicateRegistrar.registerPredicates() {
    register(predicate)
  }

  override fun getContributions(
    scopeClassId: ClassId,
    typeResolverFactory: MetroFirTypeResolver.Factory,
  ): List<MetroContributionExtension.Contribution> {
    return annotatedClasses.flatMap { parentSymbol ->
      val annotationScopeClassId =
        extractScopeClassId(
          parentSymbol,
          ContributesMultibindingScopedIds.CONTRIBUTES_MULTIBINDING_SCOPED_CLASS_ID,
          session,
        ) ?: return@flatMap emptyList()

      if (annotationScopeClassId != scopeClassId) return@flatMap emptyList()

      val contributionInterfaceClassId =
        ContributesMultibindingScopedIds.contributionClassId(parentSymbol.classId)
      val holderClassId = ContributesMultibindingScopedIds.holderClassId(parentSymbol.classId)

      val contributionSymbol =
        session.symbolProvider.getClassLikeSymbolByClassId(contributionInterfaceClassId)
          as? FirRegularClassSymbol
      val holderSymbol =
        session.symbolProvider.getClassLikeSymbolByClassId(holderClassId) as? FirRegularClassSymbol

      buildList {
        if (holderSymbol != null) {
          add(
            MetroContributionExtension.Contribution(
              supertype = holderSymbol.defaultType(),
              replaces = emptyList(),
              originClassId = holderClassId,
            )
          )
        }
        if (contributionSymbol != null) {
          add(
            MetroContributionExtension.Contribution(
              supertype = contributionSymbol.defaultType(),
              replaces = emptyList(),
              originClassId = contributionInterfaceClassId,
            )
          )
        }
      }
    }
  }

  @AutoService(MetroContributionExtension.Factory::class)
  public class Factory : MetroContributionExtension.Factory {
    override fun create(
      session: FirSession,
      options: MetroOptions,
      compatContext: CompatContext,
    ): MetroContributionExtension {
      return ContributesMultibindingScopedMetroExtension(session)
    }
  }
}
