plugins {
  id 'com.squareup.lib'
  id 'com.squareup.metro.extensions'
  alias libs.plugins.metro
}

metro {
  compilerVersionAliases.put('2.4.0-Beta1', '2.4.0-dev-2124')
}

dependencies {
  implementation project(':integration-tests:lib')
  implementation project(':stubs')
  testImplementation libs.kotlin.test
}
